services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
      - redis
    env_file:
      - .env
  db:
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - 6389:6379

  s3:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    volumes:
      - ./docker/minio/data:/data
